---
- name: creating current cert directory
  file: path=/etc/ssl/{{ le.user }}/letsencrypt/{{ ansible_date_time.year }}-{{ ansible_date_time.month }} state=directory owner={{ le.user }} group={{ le.user }} mode=0700
  register: directory

- name: Copy cert
  when: directory| success
  copy:  src={{ le.cert }} dest=/etc/ssl/{{ le.user }}/letsencrypt/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}/cert.pem  owner={{ le.user }} group={{ le.user }} mode=0600

- name: Copy key
  when: directory| success
  copy:  src={{ le.key }} dest=/etc/ssl/{{ le.user }}/letsencrypt/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}/key.pem  owner={{ le.user }} group={{ le.user }} mode=0600

- name: generate nginx config
  template: src=nginx-ssl-le.j2 dest=/etc/ssl/{{ le.user }}/letsencrypt/nginx-ssl.conf owner={{ le.user }} group={{ le.user }}
  register: nginx_config

- name: validate nginx conf
  shell: sh -c "sudo nginx -t"
  changed_when: false
  notify: reload nginx
