---
- name: creating current cert directory
  file: path=/etc/ssl/{{ le.user }}/letsencrypt/{{ ansible_date_time.year }}-{{ ansible_date_time.month }} state=directory owner={{ le.user }} group={{ le.user }} mode=0700
  register: directory

- name: Copy cert
  when: directory| success
  copy:  src={{ le.cert }} dest=/etc/ssl/{{ le.user }}/letsencrypt/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}/cert.pem  owner={{ le.user }} group={{ le.user }} mode=0600

- name: Copy key
  when: directory| success
  copy:  src={{ le.key }} dest=/etc/ssl/{{ le.user }}/letsencrypt/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}/key.pem  owner={{ le.user }} group={{ le.user }} mode=0600

- name: generate nginx config
  template: src=nginx-ssl-le.j2 dest=/etc/ssl/{{ le.user }}/letsencrypt/nginx-ssl.conf owner={{ le.user }} group={{ le.user }}
  notify: reload nginx
  register: nginx_config
  
- local_action: mail
                to="{{ le.mail_recipient }}"
                subject='Ansible-report nginx-ssl configuration ({{ ansible_date_time.year }}-{{ ansible_date_time.month }})'
                body='The nginx-ssl configuration on {{ ansible_hostname }} has been successfully renewed.'
  when: nginx_config
